#!/bin/bash


NEBULA_ADDRESS='0X124234234'
CHAIN_TYPE='waves'

# GRAVITY_HOME=/etc/gravity-oracle
GRAVITY_PUBLIC_LEDGER_RPC='A'
GRAVITY_TARGET_CHAIN_NODE_URL='B'
GRAVITY_EXTRACTOR_ENDPOINT='C'


docker run -it \
	-e NEBULA_ADDRESS=$NEBULA_ADDRESS \
	-e CHAIN_TYPE=$CHAIN_TYPE \
	-e GRAVITY_PUBLIC_LEDGER_RPC=$GRAVITY_PUBLIC_LEDGER_RPC \
	-e GRAVITY_TARGET_CHAIN_NODE_URL=$GRAVITY_TARGET_CHAIN_NODE_URL \
	-e GRAVITY_EXTRACTOR_ENDPOINT=$GRAVITY_EXTRACTOR_ENDPOINT \
	gravity-oracle
